
language: node_js
node_js:
  - "4"

# whitelist
# branches:
#   only:
#     - master

before_script:
  - npm install -g gulp
  - npm install
script: gulp unit

# before_script:
#   coffee -c -o specs specs